setup.py: add dependency of kiwisolver
not sure why it's required, but if not specify here,
it will be needed to compile from source.
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>